[telegram]
telegram-token=911971525:AAExau9c1NCnZMeFOZ-xEvkOyNmwtgJJbA8

[data]
ques-col=question
ans-col=answer
ans-cat-col=answer-category
ques-cat-col=question-category
train-file-name=consumer_questions.csv

[mongo-data]
db=tulo_train
url=mongodb://127.0.0.1:27017/tulo_train
#db=heroku_2r6cnrs1
#url=mongodb://heroku_2r6cnrs1:os02s46gjpp2b0mio9qa4o3g8g@ds229078.mlab.com:29078/heroku_2r6cnrs1
col_lang=lang
col_category=category
col_query=query
col_variables=variables
col_response=response
col_input_circumstance=input_circumstance
col_output_circumstance=output_circumstance
mongo_train_fileName=train.csv


[model-file-name]
response-classifier=CLASSIFIER_TFIDF_LOGISTIC_RESPONSE_01.sav

ans-cat-classifier=CLASSIFIER_TFIDF_LOGISTIC_ANSWERS_CATEGORY_02.sav
ques-cat-classifier=CLASSIFIER_TFIDF_LOGISTIC_QUESTIONS_CATEGORY_02.sav